### ISSUE TITLE
集成goproxy android-sdk 运行失败

### ISSUE THREAD

**Issue by 790770679** [snail007/goproxy-sdk#1]
小米8    安卓版本9.0 miui 10
>>
03-23 14:22:19.121 4134-0/com.tencent.myapplication E/Go: panic: runtime error: index out of range
    goroutine 17 [running, locked to thread]:
03-23 14:22:19.122 4134-0/com.tencent.myapplication E/Go: github.com/snail007/license/lic-checker/goinfo.GetInfoMap(0x71b2f6cfee)
    	/home/pengmeng/go/src/github.com/snail007/license/lic-checker/goinfo/goInfo_linux.go:25 +0x4e8
    github.com/snail007/license/lic-checker.Report(0x442002ea30, 0x10, 0x442002e655, 0x3, 0x442002e8f0, 0xd, 0x34630b8a000)
    	/home/pengmeng/go/src/github.com/snail007/license/lic-checker/checker.go:179 +0x18
    github.com/snail007/proxy/sdk/android-ios.StartWithLog(0x442002e8e0, 0x6, 0x442002e8f0, 0xd, 0x0, 0x0, 0x4420020070, 0xd)
    	/home/pengmeng/go/src/github.com/snail007/proxy/sdk/android-ios/sdk.go:92 +0xf4
    github.com/snail007/proxy/sdk/android-ios.Start(0x442002e8e0, 0x6, 0x442002e8f0, 0xd, 0x7100000008, 0x4420062080)
    	/home/pengmeng/go/src/github.com/snail007/proxy/sdk/android-ios/sdk.go:66 +0x40
03-23 14:22:19.123 4134-0/com.tencent.myapplication E/Go: main.proxyproxy__Start(0x71b431a160, 0x6, 0x71b3c86680, 0xd, 0x0, 0x0)
    	/tmp/gomobile-work-022422383/src/gobind/go_proxymain.go:128 +0x64
    main._cgoexpwrap_ef64ed5c78f1_proxyproxy__Start(0x71b431a160, 0x6, 0x71b3c86680, 0xd, 0x0, 0x0)
    	_cgo_gotypes.go:271 +0x64
    
    --------- beginning of crash
03-23 14:22:19.124 4134-4134/com.tencent.myapplication A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 4134 (t.myapplication), pid 4134 (t.myapplication)
03-23 14:22:19.270 4191-4191/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    Build fingerprint: 'Xiaomi/dipper/dipper:9/PKQ1.180729.001/V10.2.2.0.PEACNXM:user/release-keys'
    Revision: '0'
    ABI: 'arm64'
    pid: 4134, tid: 4134, name: t.myapplication  >>> com.tencent.myapplication <<<
    signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
        x0  0000000000000000  x1  0000000000000006  x2  0000000000000000  x3  0000000000000008
        x4  0000000000000020  x5  0000000000000000  x6  0000000000000006  x7  0000000000000000
        x8  0000000000000082  x9  00000071b33321f0  x10 000000000005eacf  x11 0000004420000600
        x12 0000000000000000  x13 0000000000000000  x14 0000000000000000  x15 0000000000000001
        x16 0000007fc374bddc  x17 00000071b3582ee0  x18 0000000000000008  x19 000000001d273a1d
        x20 00000071b3c86680  x21 0000000000000006  x22 00000071b431a160  x23 0000000000000000
        x24 0000000000000008  x25 00000072524665e0  x26 0000000000000000  x27 0000000000000000
        x28 0000004420000480  x29 0000007fc374c4f0
        sp  0000007fc374c280  lr  00000071b2b0c44c  pc  00000071b2b21c48
03-23 14:22:19.271 4191-4191/? A/DEBUG: backtrace:
        #00 pc 00000000002d3c48  /data/app/com.tencent.myapplication-2kccKH4ii9_qekSeiqLlKQ==/lib/arm64/libgojni.so

**Comment by snail007** [comment]
下一版已经修复

**Comment by 790770679** [comment]
谢谢大佬。那我直接用gomoblie 编译一下最新的goproxy就可以了？

**Comment by snail007** [comment]
等发布

**Comment by snail007** [comment]
fixed
